apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms1-pod
  template:
    metadata:
      labels:
        app: ms1-pod
    spec:
      containers:
      - name: ms1
        image: ms1:latest
        imagePullPolicy: Never 